apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-test-role-binding
subjects:
- kind: ServiceAccount
  name: user-test
  namespace: default # Replace with the namespace where the user-test ServiceAccount is located
roleRef:
  kind: ClusterRole
  name: user-test-role # Replace with the name of the ClusterRole you created in the previous step
  apiGroup: rbac.authorization.k8s.io

