apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /Users/carteramihail/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Thu, 13 Jul 2023 20:03:05 EEST
            provider: minikube.sigs.k8s.io
            version: v1.30.1
          name: cluster_info
      server: https://127.0.0.1:50285
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Thu, 13 Jul 2023 20:03:05 EEST
            provider: minikube.sigs.k8s.io
            version: v1.30.1
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: /Users/carteramihail/.minikube/profiles/minikube/client.crt
      client-key: /Users/carteramihail/.minikube/profiles/minikube/client.key
